### ISSUE TITLE
How to use this in wordpress?

### ISSUE THREAD

**Issue by lchhieu** [Rareloop/router#1]

**Comment by alexkuc** [comment]
I think it is pretty straight forward:

1. create routes - https://github.com/Rareloop/router#creating-routes
2. match request against routes - https://github.com/Rareloop/router#matching-routes-to-requests

I have defined routes directly in `functions.php` _directly_ i.e. without using any hooks/filters.
I have matched request against routes using hook `template_redirect` in `functions.php`

**Comment by adamtomat** [comment]
Also, for those looking for a WordPress framework with routing baked in then check out Lumberjack:

- https://lumberjack.rareloop.com
- https://docs.lumberjack.rareloop.com/the-basics/routing

It uses this router and has it configured out-of-the-box for you (as well as a bunch of other goodies) 👍
