### ISSUE TITLE
Install ran into a problem with my PHP version.

### ISSUE THREAD

**Issue by graphicagenda** [Rareloop/router#10]
In trying to run the lumberjack composer installation, I reached this requirement not met issue:  rareloop/router v4.4.0 requires php ^7.1 -> your php version (8.0.3) does not satisfy that requirement.

**Comment by adamtomat** [comment]
@graphicagenda thanks for the ticket. Looks like we just need to add support for PHP 8

**Comment by joelambert** [comment]
Theres a PR for this now https://github.com/Rareloop/router/pull/11

**Comment by joelambert** [comment]
Fixed by #11
