### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by mkraha** [Rareloop/router#4]
When will release will be ready with latest updates?

**Comment by joelambert** [comment]
Hi, thanks for raising an issue. Are you able to provide more information?

The latest version is `v4.3.1` and this has been tagged and is available on Packagist via Composer.

**Comment by mkraha** [comment]
Those releases are inside tags so i didn't view properly last time.
![image](https://user-images.githubusercontent.com/6831562/79482438-21515880-8011-11ea-851a-5609816ecb03.png)
