### ISSUE TITLE
Problem of integrating Symfony Request with Rareloop Router

### ISSUE THREAD

**Issue by StevenRoan** [Rareloop/router#9]
As in the document, I use following code to integrate the router.

```

$request = Request::createFromGlobals();
$response = $router->match($request);
$response->send();

```

However, I get the error that

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Rareloop\Router\Router::match() must be an instance of Psr\Http\Message\ServerRequestInterface, instance of Symfony\Component\HttpFoundation\Request given

Because the document also mentioned that  "match() accepts an instance of Symfony's Request", it is quite confused for me for the error. 

Appreciate if any advice! Thanks.

**Comment by StevenRoan** [comment]
Just found the solution. We need to convert the psr7 request/response and symphony request/response to make the function work.

reference: https://symfony.com/doc/current/components/psr7.html

**Comment by alexkuc** [comment]
Here's a working example using [laminas/laminas-diactoros](https://packagist.org/packages/laminas/laminas-diactoros) package:

```php
$router = new Router();

$router->get('test', function () {
  return '1234';
});

$request = ServerRequestFactory::fromGlobals();

$factory = new HttpFoundationFactory();

$response = $factory->createResponse($router->match($request));

$response->send();
```
